# Pebble Information File
# DO NOT DELETE. THIS FILE CONTAINS IMPORTANT INFORMATION.
[Pebble]
version = "2.0.0"

    [Pebble.Apps]
    apps = [ "calc", "spinner" ]

    [Pebble.Dev]
    modules = "public/modules"
    prvscript = "root/scripts"
    pubscript = "public/scripts"

    [Pebble.Home]
    options = [ "Apps", "Get Apps", "Help", "Preferences", "Shutdown" ]

    [Pebble.Preferences]
    username = "User"

    [Pebble.Repos.pebbleapp]
    description = "The official repository for pebble apps."
    url = "https://raw.githubusercontent.com/samrland/pebble-app/main"

    [Pebble.SysFiles]
    apps = "public/apps/apps.lua"
    home = "root/main/home.lua"
    pref = "root/main/settings.lua"

    [Pebble.UserDirs]
    apps = "public/apps"
    documents = "public/documents"
    trash = "public/trash"
